### ISSUE TITLE
will you try to use angular2-cli?

### ISSUE THREAD

**Issue by keryhu** [springboot-angular2-tutorial/angular2-app#15]
Hi,akirasosa

 I have build a angular2-app and spring boot app, refer to your work.

  now , I find  angular2-cli is concise maybe， will you plan to try?

 I want to try ,but do not know how to  set the **"outDir"**,**"Proxy To Backend"**

e.g

```
{
  "/api": {
    "target": "http://localhost:8080",
    "secure": false
  }
}
```

**and in spring boot , how to set index.html.**

```
<body>
<mpt-app />
<script th:src="|//${assetHost}/${manifest.get('polyfills.js')}|"></script>
<script th:src="|//${assetHost}/${manifest.get('vendor.js')}|"></script>
<script th:src="|//${assetHost}/${manifest.get('main.js')}|"></script>
```

**Comment by akirasosa** [comment]
@keryhu 
I have not tried it yet. I'm interested in it and @ngtools/webpack.

If you want to "Proxy To Backend", it must be that index.html is served from angular-cli server, not spring boot (API server).
