### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by thailow** [springboot-angular2-tutorial/angular2-app#19]
The frontend does not work in IE11 (only shows blank page). Any idea how to fix that? Thanks!

**Comment by thailow** [comment]
Ok, I found a solution: Added shim.min.js from node_modules/core-js/client to the src directory and referenced it with <script src="shim.min.js"></script> in the head tag of index.html .. If you know a better solution, I'd be interested...

**Comment by akirasosa** [comment]
@thailow 
I might have removed polyfills too much here.
https://github.com/springboot-angular2-tutorial/angular2-app/blob/master/src/polyfills.ts

Anyway I have to got an environment to test IE at first..

Thanks for reporting!

**Comment by akirasosa** [comment]
fixed.
https://github.com/springboot-angular2-tutorial/angular2-app/commit/d5a0c45be33b2cde6f5cd223ba1e58f47bbc7f74
