### ISSUE TITLE
Give page paraeter to /users. It's required for history back.

### ISSUE THREAD

**Issue by akirasosa** [springboot-angular2-tutorial/angular2-app#2]
1. Move to /users
2. Move to next page of /users
3. Show user detail
4. History back

Now, it's always back to first page. But it's expected to be back to page 2.

**Comment by Kravs** [comment]
How to fix that bug ? :)

**Comment by akirasosa** [comment]
@Kravs 
Here is an implementation. Take a look.
https://github.com/springboot-angular2-tutorial/angular2-app/commit/86bd413a1e0e1d64dd5490ecc2a3982c10b9ae80#diff-fe9330d62aad143933fa53e34da3cd04
