### ISSUE TITLE
Where is index.html

### ISSUE THREAD

**Issue by Kravs** [springboot-angular2-tutorial/angular2-app#7]
Sorry for dummy question, but where is entry point ?
Where `<app></app>` is located to run app ?

**Comment by akirasosa** [comment]
@Kravs 
The entry point is supposed to be rendered by server side in this example. You can see it at https://github.com/springboot-angular2-tutorial/boot-app/blob/master/src/main/resources/templates/index.html .

**Comment by Kravs** [comment]
@akirasosa Thank you, it helps :)
