### ISSUE TITLE
en external problem about how set angular2 host as “localhost or a fixed ip

### ISSUE THREAD

**Issue by keryhu** [springboot-angular2-tutorial/angular2-app#8]
hello,

  
I would like to ask a question ， if i build a spring-boot angular2 in docker .

I can set the host in spring-boot server , as  "localhost /192.168.1.110",

How set  it in angular2 ， that can be easily  tested locally or 192.168.1.110 env?

**Comment by akirasosa** [comment]
@keryhu 
You just run ```npm start```. Then, webpack-dev-server will be started. It is configured to use port 3001 as default.

https://github.com/springboot-angular2-tutorial/angular2-app/blob/8f81bd8f8b3092c5c15f4c58f652bd6f653f0842/config/webpack.dev.js#L11-L11

You can access it with something like http://yourhost:3001/main.js .

**Comment by keryhu** [comment]
@akirasosa   yes, 
I can think of the current way is that host configuration localhost ,, when development is complete, change to a fixed ip

**Comment by akirasosa** [comment]
@keryhu 
In production, you can use any servers such as S3, CloudFront and your own Nginx server to host your js files. I use CloudFlare for my [demo app](https://micropost.hana053.com/home). The main.js is served from https://cdn.hana053.com/main.5cb9cd7281b9f956d6fa.js .

Then, all you have to do is just configuring boot-app to point the location js files hosted.
https://github.com/springboot-angular2-tutorial/boot-app/blob/ddf84b0a7e1e98f47f6cbdbc1ca09a049d763ff1/src/main/resources/application.yml#L87

P.S.

In develop mode, you may want to configure the host of webpack-dev-server as ```0.0.0.0```. Then, you can access it when angular2-app is running in virtual machine or docker.

**Comment by keryhu** [comment]
Ah,yes, **webpack-dev-server as 0.0.0.0**  that 's what I urgently needed ！ Thanks very much !
